export { default as PrivacyPolicyPage } from './PrivacyPolicyPage'
export { default as TermsOfServicePage } from './TermsOfServicePage'
export { default as CookiePolicyPage } from './CookiePolicyPage'
export { default as AboutPage } from './AboutPage'
export { default as ContactPage } from './ContactPage'
export { default as FAQPage } from './FAQPage'
