import type { GateDefinition, GateType } from '@/types/simulator'

export const GATE_DEFINITIONS: Record<GateType, GateDefinition> = {
  H: {
    type: 'H',
    name: 'Hadamard',
    description: 'Creates superposition by rotating the state vector by π about the X+Z axis',
    numQubits: 1,
    numControls: 0,
    parameters: [],
    color: '#3b82f6',
    symbol: 'H',
    category: 'single-qubit',
  },
  X: {
    type: 'X',
    name: 'Pauli-X (NOT)',
    description: 'Bit flip gate - rotates the state by π around the X axis',
    numQubits: 1,
    numControls: 0,
    parameters: [],
    color: '#ef4444',
    symbol: 'X',
    category: 'single-qubit',
  },
  Y: {
    type: 'Y',
    name: 'Pauli-Y',
    description: 'Rotates the state by π around the Y axis',
    numQubits: 1,
    numControls: 0,
    parameters: [],
    color: '#22c55e',
    symbol: 'Y',
    category: 'single-qubit',
  },
  Z: {
    type: 'Z',
    name: 'Pauli-Z',
    description: 'Phase flip gate - rotates the state by π around the Z axis',
    numQubits: 1,
    numControls: 0,
    parameters: [],
    color: '#a855f7',
    symbol: 'Z',
    category: 'single-qubit',
  },
  S: {
    type: 'S',
    name: 'S Gate (√Z)',
    description: 'Rotates by π/2 around the Z axis',
    numQubits: 1,
    numControls: 0,
    parameters: [],
    color: '#06b6d4',
    symbol: 'S',
    category: 'phase',
  },
  T: {
    type: 'T',
    name: 'T Gate (π/8)',
    description: 'Rotates by π/4 around the Z axis',
    numQubits: 1,
    numControls: 0,
    parameters: [],
    color: '#f59e0b',
    symbol: 'T',
    category: 'phase',
  },
  Sdg: {
    type: 'Sdg',
    name: 'S† Gate',
    description: 'Inverse of S gate - rotates by -π/2 around the Z axis',
    numQubits: 1,
    numControls: 0,
    parameters: [],
    color: '#06b6d4',
    symbol: 'S†',
    category: 'phase',
  },
  Tdg: {
    type: 'Tdg',
    name: 'T† Gate',
    description: 'Inverse of T gate - rotates by -π/4 around the Z axis',
    numQubits: 1,
    numControls: 0,
    parameters: [],
    color: '#f59e0b',
    symbol: 'T†',
    category: 'phase',
  },
  Rx: {
    type: 'Rx',
    name: 'Rotation X',
    description: 'Rotates the state by θ around the X axis',
    numQubits: 1,
    numControls: 0,
    parameters: [{ name: 'θ', min: 0, max: 2 * Math.PI, default: Math.PI / 2, step: 0.01 }],
    color: '#ef4444',
    symbol: 'Rx',
    category: 'rotation',
  },
  Ry: {
    type: 'Ry',
    name: 'Rotation Y',
    description: 'Rotates the state by θ around the Y axis',
    numQubits: 1,
    numControls: 0,
    parameters: [{ name: 'θ', min: 0, max: 2 * Math.PI, default: Math.PI / 2, step: 0.01 }],
    color: '#22c55e',
    symbol: 'Ry',
    category: 'rotation',
  },
  Rz: {
    type: 'Rz',
    name: 'Rotation Z',
    description: 'Rotates the state by θ around the Z axis',
    numQubits: 1,
    numControls: 0,
    parameters: [{ name: 'θ', min: 0, max: 2 * Math.PI, default: Math.PI / 2, step: 0.01 }],
    color: '#a855f7',
    symbol: 'Rz',
    category: 'rotation',
  },
  U: {
    type: 'U',
    name: 'Universal Gate',
    description: 'General single-qubit unitary with 3 Euler angles',
    numQubits: 1,
    numControls: 0,
    parameters: [
      { name: 'θ', min: 0, max: Math.PI, default: Math.PI / 2, step: 0.01 },
      { name: 'φ', min: 0, max: 2 * Math.PI, default: 0, step: 0.01 },
      { name: 'λ', min: 0, max: 2 * Math.PI, default: 0, step: 0.01 },
    ],
    color: '#8b5cf6',
    symbol: 'U',
    category: 'rotation',
  },
  U1: {
    type: 'U1',
    name: 'U1 Gate',
    description: 'Single parameter phase gate',
    numQubits: 1,
    numControls: 0,
    parameters: [{ name: 'λ', min: 0, max: 2 * Math.PI, default: Math.PI / 2, step: 0.01 }],
    color: '#8b5cf6',
    symbol: 'U1',
    category: 'phase',
  },
  U2: {
    type: 'U2',
    name: 'U2 Gate',
    description: 'Two parameter single-qubit gate',
    numQubits: 1,
    numControls: 0,
    parameters: [
      { name: 'φ', min: 0, max: 2 * Math.PI, default: 0, step: 0.01 },
      { name: 'λ', min: 0, max: 2 * Math.PI, default: 0, step: 0.01 },
    ],
    color: '#8b5cf6',
    symbol: 'U2',
    category: 'rotation',
  },
  U3: {
    type: 'U3',
    name: 'U3 Gate',
    description: 'Three parameter single-qubit gate',
    numQubits: 1,
    numControls: 0,
    parameters: [
      { name: 'θ', min: 0, max: Math.PI, default: Math.PI / 2, step: 0.01 },
      { name: 'φ', min: 0, max: 2 * Math.PI, default: 0, step: 0.01 },
      { name: 'λ', min: 0, max: 2 * Math.PI, default: 0, step: 0.01 },
    ],
    color: '#8b5cf6',
    symbol: 'U3',
    category: 'rotation',
  },
  CNOT: {
    type: 'CNOT',
    name: 'CNOT (CX)',
    description: 'Controlled-NOT gate - flips target if control is |1⟩',
    numQubits: 2,
    numControls: 1,
    parameters: [],
    color: '#0ea5e9',
    symbol: '⊕',
    category: 'controlled',
  },
  CX: {
    type: 'CX',
    name: 'CX (CNOT)',
    description: 'Controlled-NOT gate - flips target if control is |1⟩',
    numQubits: 2,
    numControls: 1,
    parameters: [],
    color: '#0ea5e9',
    symbol: '⊕',
    category: 'controlled',
  },
  CZ: {
    type: 'CZ',
    name: 'Controlled-Z',
    description: 'Applies Z to target if control is |1⟩',
    numQubits: 2,
    numControls: 1,
    parameters: [],
    color: '#a855f7',
    symbol: 'CZ',
    category: 'controlled',
  },
  CY: {
    type: 'CY',
    name: 'Controlled-Y',
    description: 'Applies Y to target if control is |1⟩',
    numQubits: 2,
    numControls: 1,
    parameters: [],
    color: '#22c55e',
    symbol: 'CY',
    category: 'controlled',
  },
  SWAP: {
    type: 'SWAP',
    name: 'SWAP',
    description: 'Exchanges the states of two qubits',
    numQubits: 2,
    numControls: 0,
    parameters: [],
    color: '#f97316',
    symbol: '×',
    category: 'multi-qubit',
  },
  iSWAP: {
    type: 'iSWAP',
    name: 'iSWAP',
    description: 'SWAP with an additional i phase',
    numQubits: 2,
    numControls: 0,
    parameters: [],
    color: '#f97316',
    symbol: 'iSWAP',
    category: 'multi-qubit',
  },
  CRx: {
    type: 'CRx',
    name: 'Controlled-Rx',
    description: 'Controlled rotation around X axis',
    numQubits: 2,
    numControls: 1,
    parameters: [{ name: 'θ', min: 0, max: 2 * Math.PI, default: Math.PI / 2, step: 0.01 }],
    color: '#ef4444',
    symbol: 'CRx',
    category: 'controlled',
  },
  CRy: {
    type: 'CRy',
    name: 'Controlled-Ry',
    description: 'Controlled rotation around Y axis',
    numQubits: 2,
    numControls: 1,
    parameters: [{ name: 'θ', min: 0, max: 2 * Math.PI, default: Math.PI / 2, step: 0.01 }],
    color: '#22c55e',
    symbol: 'CRy',
    category: 'controlled',
  },
  CRz: {
    type: 'CRz',
    name: 'Controlled-Rz',
    description: 'Controlled rotation around Z axis',
    numQubits: 2,
    numControls: 1,
    parameters: [{ name: 'θ', min: 0, max: 2 * Math.PI, default: Math.PI / 2, step: 0.01 }],
    color: '#a855f7',
    symbol: 'CRz',
    category: 'controlled',
  },
  Toffoli: {
    type: 'Toffoli',
    name: 'Toffoli (CCX)',
    description: 'Double-controlled NOT gate',
    numQubits: 3,
    numControls: 2,
    parameters: [],
    color: '#0ea5e9',
    symbol: '⊕',
    category: 'controlled',
  },
  Fredkin: {
    type: 'Fredkin',
    name: 'Fredkin (CSWAP)',
    description: 'Controlled SWAP gate',
    numQubits: 3,
    numControls: 1,
    parameters: [],
    color: '#f97316',
    symbol: '×',
    category: 'controlled',
  },
  Phase: {
    type: 'Phase',
    name: 'Phase Gate',
    description: 'Applies a phase shift',
    numQubits: 1,
    numControls: 0,
    parameters: [{ name: 'φ', min: 0, max: 2 * Math.PI, default: Math.PI / 4, step: 0.01 }],
    color: '#ec4899',
    symbol: 'P',
    category: 'phase',
  },
  CPhase: {
    type: 'CPhase',
    name: 'Controlled-Phase',
    description: 'Controlled phase gate',
    numQubits: 2,
    numControls: 1,
    parameters: [{ name: 'φ', min: 0, max: 2 * Math.PI, default: Math.PI / 4, step: 0.01 }],
    color: '#ec4899',
    symbol: 'CP',
    category: 'controlled',
  },
  Reset: {
    type: 'Reset',
    name: 'Reset',
    description: 'Resets qubit to |0⟩ state',
    numQubits: 1,
    numControls: 0,
    parameters: [],
    color: '#64748b',
    symbol: '|0⟩',
    category: 'special',
  },
  Barrier: {
    type: 'Barrier',
    name: 'Barrier',
    description: 'Visual separator, prevents gate optimization across it',
    numQubits: 1,
    numControls: 0,
    parameters: [],
    color: '#64748b',
    symbol: '║',
    category: 'special',
  },
  Custom: {
    type: 'Custom',
    name: 'Custom Gate',
    description: 'User-defined gate',
    numQubits: 1,
    numControls: 0,
    parameters: [],
    color: '#6366f1',
    symbol: '?',
    category: 'special',
  },
}

export const GATE_PALETTE = {
  'Single Qubit': ['H', 'X', 'Y', 'Z'],
  'Phase': ['S', 'T', 'Sdg', 'Tdg'],
  'Rotation': ['Rx', 'Ry', 'Rz'],
  'Multi-Qubit': ['CNOT', 'CZ', 'SWAP'],
  'Advanced': ['Toffoli', 'Fredkin', 'CRx', 'CRy', 'CRz'],
  'Special': ['Reset', 'Barrier'],
} as const

export function getGateColor(gateType: GateType): string {
  return GATE_DEFINITIONS[gateType]?.color || '#64748b'
}

export function getGateSymbol(gateType: GateType): string {
  return GATE_DEFINITIONS[gateType]?.symbol || gateType
}
